project:
  type: website
  resources:
    - resume.pdf

website:
  title: "Mandy Vien"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
        
  page-footer:
    right: "&copy; 2024, Mandy Vien"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto 

editor: visual
